<?php

$config = array(
	"URL_CREDIVENTAS" => "https://crediventas.com/",
	"COMMERCE" => 35,
	"PAYMENT" => [
		"test" => true,
		// "key" => "pub_test_Pyqg1veGJUyPhLe2DmRjBHxqFzTLlOvj",
		// "integridad" => "test_integrity_cxr0ww7zAj2SBEEaSgmaYk4FN2XlLM3P",
		// "eventos" => "test_events_37sWAmmJoipDnU2DOthjGvmACqzDUiDz",

		"key" => "pub_prod_Qsb7yZ39uggnJYaOhp9WoWBTpF0TZXtq",
		"integridad" => "prod_integrity_FlQ7hbfrXM4feH8caU7rzpQO44mK9ReH",
		"eventos" => "prod_events_z6zApvm7raqSkLXdXHi429n70cEICCF6",
		// "key" => "491d6a0b6e992cf924edd8d3d088aff1",
	],
	"CODE_COMMERCE" => "63256894",
	"ROLES" => [
		"1" => "Administrador",
		"2" => "Jefe de Analistas",
		"3" => "Analista",
		"4" => "Administrador de proveedor",
		"5" => "Cliente",
		"6" => "Vendedor",
		"7" => "Contabilidad",
		"8" => "Ejecutivo / Asesor",
		"9" => "Cobranza",
		"10" => "Soporte",
		"11" => "Jurídico",
		"12" => "Soporte de Códigos",
// 		"15" => "Empresas",
	],
	"ESTADOS_HISTORIAL" => [
		"0" => "Cancelado por límite de tiempo",
		"1" => "Aprobación de cupo",
		"2" => "Cancelado por solicitud nueva de cupo",
		"3" => "Aumento de cupo por pago oportuno",
		"4" => "Cancelación de cupo por mora",
		"5" => "Preaprobado por restante de solicitud",
		"6" => "Crédito aprobado",
		"8" => "Crédito Preaprobado",
	],
	"GREMIOS" => [
		"Alimentos y bebidas" => "Alimentos y bebidas",
		"Belleza y cuidado personal" => "Belleza y cuidado personal",
		"Construccion" => "Construccion",
		"Deportes" => "Deportes",
		"Educación" => "Educación",
		"Escolar" => "Escolar",
		"Farmacia" => "Farmacia",
		"Ferretería" => "Ferretería",
		"Gourmet" => "Gourmet",
		"Instrumentos musicales" => "Instrumentos musicales",
		"Insumos agrícolas" => "Insumos agrícolas",
		"Juguetería" => "Juguetería",
		"Libros" => "Libros",
		"Movilidad" => "Movilidad",
		"Muebles y hogar" => "Muebles y hogar",
		"Mundo bebe" => "Mundo bebe",
		"Mundo mascotas" => "Mundo mascotas",
		"Papelería" => "Papelería",
		"Químicos" => "Químicos",
		"Salud" => "Salud",
		"Seguros" => "Seguros",
		"Tecnología" => "Tecnología",
		"Textiles" => "Textiles",
		"Vehiculos" => "Vehiculos",
		"Vestuario, calzado y accesorios" => "Vestuario, calzado y accesorios",
		"Viajes" => "Viajes",
		"Viajes y turismo" => "Viajes y turismo",
		"Otros" => "Otros",
	],
	"ACCOUNT_TYPES" => [
		"AHORROS" => "AHORROS",
		"CORRIENTE" => "CORRIENTE"
	],
	"YESNO"=>[
		"1" => "SI",
		"0" => "NO",
	],
	"PLANES" => [
		"1" => "Plan A",
		"2" => "Plan B"
	],
	"TYPE_APPROBE" => [
		"0" => "Valor mínimo",
		"1"	=> "Valor máximo",
		"2" => "Promedio"
	],
	"PAYMENT_TYPE_SHOPS" => [
		"1" => "Contado (efectivo)",
		"2"	=> "Tarjeta de crédito",
		"3" => "Financiación"
	],
	"MORADAY" => [
		"30" => "30",
		"60" => "60",
		"90" => "90"
	],
	"PLAN_COST" => [
		"1" => 380800,
		"2" => 190400
	],
	"PLAN_COST_VALUES" => [
		"1" => [
			"min" => 4,
			"max" => 0,
		],
		"2" => [
			"min" => 0,
			"max" => 0
		]
	],
	"PRODUCT_LIST" => [
		"1" => "Cámara de seguridad",
		"2" => "Software contable",
		"3" => "Software administación",
		"4" => "Página WEB",
		"5" => "Venta en redes sociales",
		"6" => "Manejo de seguros"
	],
	'Email' => array(
		'contact_mail' 	=> array('prodigital11@gmail.com' => 'Notificación ZÍRO'),
	),
	"Identification_TYPE" => array(
		"CC" => "Cédula de ciudadanía",
	),
	"CCI_TYPE" => array(
		"si" => "Sí",
		"no" => "No"
	),
	"ADDRESS_TYPE" =>[
		"1" => "Dirección Residencial",
		"2" => "Dirección Laboral"
	],
	"REFERENCES_TYPE" => [
		"1" => "Referencia Personal",
		"2" => "Referencia Familiar",
		"3" => "Referencia Laboral",
	],
	"TYPE_COMMENT"=>[
		"Las fotos del documento no son legibles" => "Las fotos del documento no son legibles",
		"Una de las referencias no contesta el teléfono" => "Una de las referencias no contesta el teléfono",
		"Hay problemas con el documento de identidad" => "Hay problemas con el documento de identidad",
	],
	"TIPO_DE_CONTRATO" => [
		"Indefinido" =>	"Indefinido",
		"Término fijo" => "Término fijo",
		"Prestación de servicios" => "Prestación de servicios",
		"Obra labor" =>	"Obra labor",
		"Ninguno" => "Ninguno"
	],
	"OCUPACIONES" => [
		"Empleado",
		"Independiente",
		"Pensionado",
		"Desempleado",
		"No trabaja"
	],
	"PARENTESCO" => [
        'Padre/Madre',
        'Hermanos',
        'Tios',
        'Abuelos'
	],
	"PERFIL" => [
		"Jefe Inmediato",
		"Recursos Humanos"
	],
	"PROCREDITO" => [
		"RIESGO_SCORE_CREDITICIO" => [
			"ALTO" => 0,
			"MEDIO ALTO" => 1,
			"MEDIO - ALTO" => 1,
			"MEDIO" => 2,5,
			"MEDIO BAJO" => 4,
			"MEDIO - BAJO" => 4,
			"BAJO" => 5,
		],
		"OBLIGACIONES_EN_MORA" => [
			"0 días" => 5,
			"30 días" => 3,
			"60 días" => 2,
			"90 días" => 0.5,
			"Más de 90 días" => 0,
		],
		"OBLIGACIONES_CANCELADAS" => [
			"4" => 5,
			"3" => 4.5,
			"2" => 4,
			"1" => 3,
			"0" => 1
		],
		"HABITO_DE_PAGO" => [
			"Al día" => 5,
			"Mora 30" => 4,
			"Mora 60" => 3,
			"Mora 90" => 1,
		],
		"CAPACIDAD_DE_ENDEUDAMIENTO" => [
			"86% a 100%" => 5,
			"70%-85%" => 4,
			"50%-69%" => 3,
			"0-49%" => 0,
		],
		"OCUPACION" => [
			"Empleado" =>	5,
			"Independiente" =>	4,
			"No trabaja" =>	3.5,
			"Estudiante" =>	3.5,
			"Pensionado" =>	5,
		],
		"TIPO_DE_CONTRATO" => [
			"Indefinido" =>	5,
			"Término fijo" =>	4,
			"Prestación de servicios" =>	3,
			"Obra labor" =>	3,
			"Ninguno" => 1
		]
	],
	"PONDERADO" => [
		"RIESGO_SCORE_CREDITICIO" => 0.33,
		"OBLIGACIONES_EN_MORA" => 0.15,
		"OBLIGACIONES_CANCELADAS" => 0.15,
		"HABITO_DE_PAGO" => 0.15,
		"CAPACIDAD_DE_ENDEUDAMIENTO" => 0.1,
		"OCUPACION" => 0.06,
		"TIPO_DE_CONTRATO" => 0.06
	],
	"REJECT_REASONS" => [
		"Reportado en centrales" => "Reportado en centrales",
		"No tiene capacidad de endeudamiento" => "No tiene capacidad de endeudamiento",
		"Mora en entidades" => "Mora en entidades",
		"Sin historial crediticio" => "Sin historial crediticio",
		"No cumple con scoring" => "No cumple con scoring",
		"Política laboral" => "Política laboral",
	],
	"BANCOS" => [
		"Banco de Bogotá" => "Banco de Bogotá",
		"Banco Popular" => "Banco Popular",
		"Banco CorpBanca" => "Banco CorpBanca",
		"Bancolombia" => "Bancolombia",
		"Citibank" => "Citibank",
		"Banco GNB Sudameris" => "Banco GNB Sudameris",
		"BBVA Colombia" => "BBVA Colombia",
		"Banco de Occidente" => "Banco de Occidente",
		"Banco Caja Social" => "Banco Caja Social",
		"Davivienda" => "Davivienda",
		"Scotiabank" => "Scotiabank",
		"Banagrario" => "Banagrario",
		"AV Villas" => "AV Villas",
		"Banco Credifinanciera" => "Banco Credifinanciera",
		"Bancamía S.A." => "Bancamía S.A.",
		"Banco W S.A." => "Banco W S.A.",
		"Bancoomeva" => "Bancoomeva",
		"Finandina" => "Finandina",
		"Banco Falabella S.A." => "Banco Falabella S.A.",
		"Banco Pichincha S.A." => "Banco Pichincha S.A.",
		"Banco Santander" => "Banco Santander",
		"Banco Mundo Mujer" => "Banco Mundo Mujer",
		"Banco Multibank" => "Banco Multibank",
		"Banco Serfinanzas" => "Banco Serfinanzas",
		"Corficolombiana" => "Corficolombiana",
		"Banca de Inversión Bancolombia" => "Banca de Inversión Bancolombia",
		"BNP Paribas" => "BNP Paribas",
		"Giros y Finanzas" => "Giros y Finanzas",
		"Tuya" => "Tuya",
		"Leasing Bancoldex" => "Leasing Bancoldex",
		"Financiera DANN Regional" => "Financiera DANN Regional",
		"Credifamilia" => "Credifamilia",
		"CREZCAMOS" => "CREZCAMOS",
		"FINANCIERA JURISCOOP C.F." => "FINANCIERA JURISCOOP C.F.",
		"Bancoldex" => "Bancoldex",
		"Findeter" => "Findeter",
		"Financiera de Desarrollo Nacional S.A" => "Financiera de Desarrollo Nacional S.A",
		"Finagro" => "Finagro",
		"Nequi" => "Nequi",
		"Daviplata" => "Daviplata",
		"Rappi Pay" => "Rappi Pay",
	],
	"TYPES_PAYMENT" => [
		"1" => "Pago a Capital",
		"2" => "Pago a Otros cargos",
		"3" => "Pago a Intereses",
		"4" => "Pago a Mora",
		"5" => "Pago a Honorarios",
		"6" => "Pago a Otros generados por incumplimiento de varias cuotas",
		"7" => "Pago a Intereses generados por incumplimiento de varias cuotas",
		"8" => "Pago a Mora generados por incumplimiento de varias cuotas",
	],
	"MONTHS" => [
		1  => 'Enero',
		2  => 'Febrero',
		3  => 'Marzo',
		4  => 'Abril',
		5  => 'Mayo',
		6  => 'Junio',
		7  => 'Julio',
		8  => 'Agosto',
		9  => 'Septiembre',
		10  => 'Octubre',
		11  => 'Noviembre',
		12  => 'Diciembre'
	],
	"COLORS" => [
		1  => '#d20a11',
		2  => '#4a4a49',
		3  => '#e83e8c',
		4  => '#dedede',
		5  => '#6f42c1',
		6  => '#3e95cd',
		7  => '#c00d0d',
		8  => '#ffc107',
		9  => '#09a92d',
		10  => '#0c4bab',
		11  => '#4a4a49',
		12  => '#dedede'
	],
	"DEPARTAMENTOS" => [
		"AMAZONAS",
		"ANTIOQUIA",
		"ARAUCA",
		"ARCHIPIELAGO DE SAN ANDRES",
		 "ATLANTICO",
		 "BOLIVAR",
		 "BOYACA",
		 "CALDAS",
		 "CAQUETA",
		 "CASANARE",
		 "CAUCA",
		 "CESAR",
		 "CHOCO",
		 "CORDOBA",
		 "CUNDINAMARCA",
		 "DISTRITO CAPITAL",
		 "GUAINIA",
		 "GUAVIARE",
		 "HUILA",
		 "LA GUAJIRA",
		 "MAGDALENA",
		 "META",
		 "NARIÑO",
		 "NORTE DE SANTANDER",
		 "PUTUMAYO",
		 "QUINDIO",
		 "RISARALDA",
		 "SANTANDER",
		 "SUCRE",
		 "TOLIMA",
		 "VALLE DEL CAUCA",
		 "VAUPES",
	  "VICHADA"
	],
	"CIUDADES" => [
		 "AMAZONAS" => [
		 	"LETICIA",
		 	"EL ENCANTO",
		 	"LA CHORRERA",
		 	"LA PEDRERA",
		 	"LA VICTORIA",
		 	"MIRITI - PARANA",
		 	"PUERTO ALEGRIA",
		 	"PUERTO ARICA",
		 	"PUERTO NARIÑO",
		 	"PUERTO SANTANDER",
		 	"TARAPACA",
		 ],
		"ANTIOQUIA" => [
			"MEDELLIN",
			"ABEJORRAL",
			"ABRIAQUI",
			"ALEJANDRIA",
			"AMAGA",
			"AMALFI",
			"ANDES",
			"ANGELOPOLIS",
			"ANGOSTURA",
			"ANORI",
			"SANTAFE DE ANTIOQUIA",
			"ANZA",
			"APARTADO",
			"ARBOLETES",
			"ARGELIA",
			"ARMENIA MANTEQUILLA",
			"BARBOSA",
			"BELMIRA",
			"BELLO",
			"BETANIA",
			"BETULIA",
			"CIUDAD BOLIVAR",
			"BRICEÑO",
			"BURITICA",
			"CACERES",
			"CAICEDO",
			"CALDAS",
			"CAMPAMENTO",
			"CAÑASGORDAS",
			"CARACOLI",
			"CARAMANTA",
			"CAREPA",
			"EL CARMEN DE VIBORAL",
			"CAROLINA DEL PRINCIPE",
			"CAUCASIA",
			"CHIGORODO",
			"CISNEROS",
			"COCORNA",
			"CONCEPCION",
			"CONCORDIA",
			"COPACABANA",
			"DABEIBA",
			"DON MATIAS",
			"EBEJICO",
			"EL BAGRE",
			"ENTRERRIOS",
			"ENVIGADO",
			"FREDONIA",
			"FRONTINO",
			"GIRALDO",
			"GIRARDOTA",
			"GOMEZ PLATA",
			"GRANADA",
			"GUADALUPE",
			"GUARNE",
			"GUATAPE",
			"HELICONIA",
			"HISPANIA",
			"ITAGUI",
			"ITUANGO",
			"JARDIN",
			"JERICO",
			"LA CEJA",
			"LA ESTRELLA",
			"LA PINTADA",
			"LA UNION",
			"LIBORINA",
			"MACEO",
			"MARINILLA",
			"MONTEBELLO",
			"MURINDO",
			"MUTATA",
			"NARIÑO",
			"NECOCLI",
			"NECHI",
			"OLAYA",
			"EL PEÑOL",
			"PEQUE",
			"PUEBLO RICO",
			"PUERTO BERRIO",
			"PUERTO NARE",
			"PUERTO TRIUNFO",
			"REMEDIOS",
			"EL RETIRO",
			"RIONEGRO",
			"SABANA LARGA",
			"SABANETA",
			"SALGAR",
			"SAN ANDRES DE CUERQUIA",
			"SAN CARLOS",
			"SAN FRANCISCO",
			"SAN JERONIMO",
			"SAN JOSE DE LA MONTAÑA",
			"SAN JUAN DE URABA",
			"SAN LUIS",
			"SAN PEDRO DE LOS MILAGROS",
			"SAN PEDRO DE URABA",
			"SAN RAFAEL",
			"SAN ROQUE",
			"SAN VICENTE",
			"SANTA BARBARA",
			"SANTA ROSA DE OSOS",
			"SANTO DOMINGO",
			"EL SANTUARIO",
			"SEGOVIA",
			"SONSON",
			"SOPETRAN",
			"TAMESIS",
			"TARAZA",
			"TARSO",
			"TITIRIBI",
			"TOLEDO",
			"TURBO",
			"URAMITA",
			"URRAO",
			"VALDIVIA",
			"VALPARAISO",
			"VEGACHI",
			"VENECIA",
			"VIGIA DEL FUERTE",
			"YALI",
			"YARUMAL",
			"YOLOMBO",
			"YONDO",
			"ZARAGOZA",
			"CURRULAO",
		],
		 "ARAUCA" => [
		 	"ARAUCA",
		 	"PUERTO NARIÑO",
		 	"ARAUQUITA",
		 	"CRAVO NORTE",
		 	"FORTUL",
		 	"PUERTO RONDON",
		 	"SARAVENA",
		 	"TAME",
		 ],
		 "ARCHIPIELAGO DE SAN ANDRES" => [
		 	"SAN ANDRES",
		 	"PROVIDENCIA"
		 ],
		 "ATLANTICO" => [
		 	"BARRANQUILLA",
		 	"BARANOA",
		 	"CAMPO DE LA CRUZ",
		 	"CANDELARIA",
		 	"GALAPA",
		 	"JUAN DE ACOSTA",
		 	"LURUACO",
		 	"MALAMBO",
		 	"MANATI",
		 	"PALMAR DE VARELA",
		 	"PIOJO",
		 	"POLO NUEVO",
		 	"PONEDERA",
		 	"PUERTO COLOMBIA",
		 	"REPELON",
		 	"SABANAGRANDE",
		 	"SABANALARGA",
		 	"SANTA LUCIA",
		 	"SANTO TOMAS",
		 	"SOLEDAD",
		 	"SUAN",
		 	"TUBARA",
		 	"USIACURI",
		 ],
		 "BOLIVAR" => [
		 	"CARTAGENA DE INDIAS",
		 	"ACHI",
		 	"ALTOS DEL ROSARIO",
		 	"ARENAL",
		 	"ARJONA",
		 	"ARROYO HONDO",
		 	"BARRANCO DE LOBA",
		 	"CALAMAR",
		 	"CANTAGALLO",
		 	"CICUCO",
		 	"CORDOBA",
		 	"CLEMENCIA",
		 	"EL CARMEN DE BOLIVAR",
		 	"EL GUAMO",
		 	"EL PEÑON",
		 	"HATILLO DE LOBA",
		 	"MAGANGUE",
		 	"MAHATES",
		 	"MARGARITA",
		 	"MARIA LA BAJA",
		 	"MONTECRISTO",
		 	"MOMPOS",
		 	"MORALES",
		 	"PINILLOS",
		 	"REGIDOR",
		 	"RIO VIEJO",
		 	"SAN CRISTOBAL",
		 	"SAN ESTANISLAO",
		 	"SAN FERNANDO",
		 	"SAN JACINTO",
		 	"SAN JACINTO DEL CAUCA",
		 	"SAN JUAN NEPOMUCENO",
		 	"SAN MARTIN DE LOBA",
		 	"SAN PABLO",
		 	"SANTA CATALINA",
		 	"SANTA ROSA NORTE",
		 	"SANTA ROSA DEL SUR",
		 	"SIMITI",
		 	"SOPLAVIENTO",
		 	"TALAIGUA NUEVO",
		 	"TIQUISIO",
		 	"TURBACO",
		 	"TURBANA",
		 	"NOROSI",
		 	"VILLANUEVA",
		 	"ZAMBRANO",
		 ],
		 "BOYACA" => [
		 	"TUNJA",
		 	"TUTAZA",
		 	"ALMEIDA",
		 	"AQUITANIA",
		 	"ARCABUCO",
		 	"BELEN",
		 	"BERBEO",
		 	"BETEITIVA",
		 	"BOAVITA",
		 	"BOYACA",
		 	"BRICEÑO",
		 	"BUENAVISTA",
		 	"BUSBANZA",
		 	"CAMPOHERMOSO",
		 	"CERINZA",
		 	"CHINAVITA",
		 	"CHIQUINQUIRA",
		 	"CHISCAS",
		 	"CHITA",
		 	"CHITARAQUE",
		 	"CHIVATA",
		 	"CIENEGA",
		 	"COMBITA",
		 	"COPER",
		 	"CORRALES",
		 	"COVARACHIA",
		 	"CUBARA",
		 	"CUCAITA",
		 	"CUITIVA",
		 	"CHIQUIZA",
		 	"CHIVOR",
		 	"DUITAMA",
		 	"EL COCUY",
		 	"EL ESPINO",
		 	"FIRAVITOBA",
		 	"FLORESTA",
		 	"GACHANTIVA",
		 	"GAMEZA",
		 	"GARAGOA",
		 	"GUACAMAYAS",
		 	"GUATEQUE",
		 	"GUAYATA",
		 	"GÜICAN",
		 	"IZA",
		 	"JENESANO",
		 	"JERICO",
		 	"LABRANZAGRANDE",
		 	"LA CAPILLA",
		 	"LA VICTORIA",
		 	"LA UVITA",
		 	"VILLA DE LEYVA",
		 	"MACANAL",
		 	"MARIPI",
		 	"MIRAFLORES",
		 	"MONGUA",
		 	"MONGUI",
		 	"MONIQUIRA",
		 	"MOTAVITA",
		 	"MUZO",
		 	"NOBSA",
		 	"NUEVO COLON",
		 	"OICATA",
		 	"OTANCHE",
		 	"PACHAVITA",
		 	"PAEZ",
		 	"PAIPA",
		 	"PAJARITO",
		 	"PANQUEBA",
		 	"PAUNA",
		 	"PAYA",
		 	"PAZ DE RIO",
		 	"PESCA",
		 	"PISBA",
		 	"PUERTO BOYACA",
		 	"QUIPAMA",
		 	"RAMIRIQUI",
		 	"RAQUIRA",
		 	"RONDON",
		 	"SABOYA",
		 	"SACHICA",
		 	"SAMACA",
		 	"SAN EDUARDO",
		 	"SAN JOSE DE PARE",
		 	"SAN LUIS DE GACENO",
		 	"SAN MATEO",
		 	"SAN MIGUEL DE SEMA",
		 	"SAN PABLO DE BORBUR",
		 	"SANTANA",
		 	"SANTA MARIA",
		 	"SANTA ROSA DE VITERBO",
		 	"SANTA SOFIA",
		 	"SATIVANORTE",
		 	"SATIVASUR",
		 	"SIACHOQUE",
		 	"SOATA",
		 	"SABANALARGA",
		 	"SOCOTA",
		 	"SOCHA",
		 	"SOGAMOSO",
		 	"SOMONDOCO",
		 	"SORA",
		 	"SOTAQUIRA",
		 	"SORACA",
		 	"SUSACON",
		 	"SUTAMARCHAN",
		 	"SUTATENZA",
		 	"TASCO",
		 	"TENZA",
		 	"TIBANA",
		 	"TIBASOSA",
		 	"TINJACA",
		 	"TIPACOQUE",
		 	"TOCA",
		 	"TOGÜI",
		 	"TOPAGA",
		 	"TOTA",
		 	"TUNUNGUA",
		 	"TURMEQUE",
		 	"TUTA",
		 	"TUTASA",
		 	"UMBITA",
		 	"VENTAQUEMADA",
		 	"VIRACACHA",
		 	"ZETAQUIRA",
		 ],
		 "CALDAS" => [
		 	"MANIZALES",
		 	"AGUADAS",
		 	"ANSERMA",
		 	"ARANZAZU",
		 	"BELALCAZAR",
		 	"CHINCHINA",
		 	"FILADELFIA",
		 	"LA DORADA",
		 	"LA MERCED",
		 	"MANZANARES",
		 	"MARMATO",
		 	"MARQUETALIA",
		 	"MARULANDA",
		 	"NEIRA",
		 	"NORCASIA",
		 	"PACORA",
		 	"PALESTINA",
		 	"PENSILVANIA",
		 	"RIOSUCIO",
		 	"RISARALDA",
		 	"SALAMINA",
		 	"SAMANA",
		 	"SAN JOSE",
		 	"SUPIA",
		 	"VICTORIA",
		 	"VILLAMARIA",
		 	"VITERBO",
		 ],
		 "CAQUETA" => [
		 	"FLORENCIA",
		 	"ALBANIA",
		 	"BELEN DE LOS ANDAQUIES",
		 	"CARTAGENA DEL CHAIRA",
		 	"CURILLO",
		 	"EL DONCELLO",
		 	"EL PAUJIL",
		 	"LA MONTAÑITA",
		 	"MILAN",
		 	"MORELIA",
		 	"PUERTO RICO",
		 	"SAN JOSE DE LA FRAGUA",
		 	"SAN VICENTE DEL CAGUAN",
		 	"SOLANO",
		 	"SOLITA",
		 	"VALPARAISO",
		 ],
		 "CASANARE" => [
		 	"YOPAL",
		 	"AGUAZUL",
		 	"CHAMEZA",
		 	"HATO COROZAL",
		 	"LA SALINA",
		 	"MANI",
		 	"MONTERREY",
		 	"NUNCHIA",
		 	"OROCUE",
		 	"PAZ DE ARIPORO",
		 	"PORE",
		 	"RECETOR",
		 	"SABANALARGA",
		 	"SACAMA",
		 	"SAN LUIS DE PALENQUE",
		 	"TAMARA",
		 	"TAURAMENA",
		 	"TRINIDAD",
		 	"VILLANUEVA",
		 ],
		 "CAUCA" => [
		 	"POPAYAN",
		 	"GUACHENE",
		 	"ALMAGUER",
		 	"ARGELIA",
		 	"BALBOA",
		 	"BOLIVAR",
		 	"BUENOS AIRES",
		 	"CAJIBIO",
		 	"CALDONO",
		 	"CALOTO",
		 	"CORINTO",
		 	"EL TAMBO",
		 	"FLORENCIA",
		 	"GUAPI",
		 	"INZA",
		 	"JAMBALO",
		 	"LA SIERRA",
		 	"LA VEGA",
		 	"LOPEZ DE MICAY",
		 	"MERCADERES",
		 	"MIRANDA",
		 	"MORALES",
		 	"PADILLA",
		 	"PAEZ - BELALCAZAR",
		 	"PATIA - EL BORDO",
		 	"PIAMONTE",
		 	"PIENDAMO",
		 	"PUERTO TEJADA",
		 	"PURACE - COCONUCO",
		 	"ROSAS",
		 	"SAN SEBASTIAN",
		 	"SANTANDER DE QUILICHAO",
		 	"SANTA ROSA",
		 	"SILVIA",
		 	"SOTARA - PAISPAMBA",
		 	"SUAREZ",
		 	"SUCRE",
		 	"TIMBIO",
		 	"TIMBIQUI",
		 	"TORIBIO",
		 	"TOTORO",
		 	"VILLA RICA",
		 ],
		 "CESAR" => [
		 	"VALLEDUPAR",
		 	"AGUACHICA",
		 	"CODAZZI",
		 	"ASTREA",
		 	"BECERRIL",
		 	"BOSCONIA",
		 	"CHIMICHAGUA",
		 	"CHIRIGUANA",
		 	"CARACOLICITO",
		 	"CURUMANI",
		 	"EL COPEY",
		 	"EL PASO",
		 	"GAMARRA",
		 	"GONZALEZ",
		 	"LA GLORIA",
		 	"LA JAGUA DE IBIRICO",
		 	"MANAURE",
		 	"PAILITAS",
		 	"PELAYA",
		 	"PUEBLO BELLO",
		 	"RIO DE ORO",
		 	"LA PAZ",
		 	"SAN ALBERTO",
		 	"SAN DIEGO",
		 	"SAN MARTIN DEL CESAR",
		 	"TAMALAMEQUE",
		 ],
		 "CHOCO" => [
		 	"QUIBDO",
		 	"ACANDI",
		 	"ALTO BAUDO",
		 	"ATRATO",
		 	"BAGADO",
		 	"BAHIA SOLANO",
		 	"BAJO BAUDO (PIZARRO)",
		 	"BELEN DE BAJIRA",
		 	"BOJAYA (BELLAVISTA)",
		 	"EL CANTON DEL SAN PABLO",
		 	"CARMEN DEL DARIEN",
		 	"CERTEGUI",
		 	"CONDOTO",
		 	"EL CARMEN DE ATRATO",
		 	"EL LITORAL DEL SAN JUAN",
		 	"ISTMINA",
		 	"JURADO",
		 	"LLORO",
		 	"MEDIO ATRATO",
		 	"MEDIO BAUDO",
		 	"MEDIO SAN JUAN",
		 	"NOVITA",
		 	"NUQUI",
		 	"RIO IRO",
		 	"RIO QUITO",
		 	"RIOSUCIO",
		 	"SAN JOSE DEL PALMAR",
		 	"SIPI",
		 	"TADO",
		 	"UNGUIA",
		 	"UNION PANAMERICANA",
		 ],
		 "CORDOBA" => [
		 	"SAN JOSE DE URE",
		 	"TUCHIN",
		 	"MONTERIA",
		 	"AYAPEL",
		 	"BUENAVISTA",
		 	"CANALETE",
		 	"CERETE",
		 	"CHIMA",
		 	"CHINU",
		 	"CIENAGA DE ORO",
		 	"COTORRA",
		 	"LA APARTADA",
		 	"LORICA",
		 	"LOS CORDOBAS",
		 	"MOMIL",
		 	"MONTELIBANO",
		 	"MOÑITOS",
		 	"PLANETA RICA",
		 	"PUEBLO NUEVO",
		 	"PUERTO ESCONDIDO",
		 	"PUERTO LIBERTADOR",
		 	"PURISIMA",
		 	"SAHAGUN",
		 	"SAN ANDRES DE SOTAVENTO",
		 	"SAN ANTERO",
		 	"SAN BERNARDO DEL VIENTO",
		 	"SAN CARLOS",
		 	"SAN PELAYO",
		 	"TIERRALTA",
		 	"VALENCIA",
		 ],
		 "CUNDINAMARCA" => [
		 	"AGUA DE DIOS",
		 	"ALBAN",
		 	"ANAPOIMA",
		 	"ANOLAIMA",
		 	"ARBELAEZ",
		 	"BELTRAN",
		 	"BITUIMA",
		 	"BOJACA",
		 	"CABRERA",
		 	"CACHIPAY",
		 	"CAJICA",
		 	"CAPARRAPI",
		 	"CAQUEZA",
		 	"CARMEN DE CARUPA",
		 	"CHAGUANI",
		 	"CHIA",
		 	"CHIPAQUE",
		 	"CHOACHI",
		 	"CHOCONTA",
		 	"COGUA",
		 	"COTA",
		 	"CUCUNUBA",
		 	"EL COLEGIO",
		 	"EL PEÑON",
		 	"EL ROSAL",
		 	"FACATATIVA",
		 	"FOMEQUE",
		 	"FOSCA",
		 	"FUNZA",
		 	"FUQUENE",
		 	"FUSAGASUGA",
		 	"GACHALA",
		 	"GACHANCIPA",
		 	"GACHETA",
		 	"GAMA",
		 	"GIRARDOT",
		 	"GRANADA",
		 	"GUACHETA",
		 	"GUADUAS",
		 	"GUASCA",
		 	"GUATAQUI",
		 	"GUATAVITA",
		 	"GUAYABAL DE SIQUIMA",
		 	"GUAYABETAL",
		 	"GUTIERREZ",
		 	"JERUSALEN",
		 	"JUNIN",
		 	"LA CALERA",
		 	"LA MESA",
		 	"LA PALMA",
		 	"LA PEÑA",
		 	"LA VEGA",
		 	"LENGUAZAQUE",
		 	"MACHETA",
		 	"MADRID",
		 	"MANTA",
		 	"MEDINA",
		 	"MOSQUERA",
		 	"NARIÑO",
		 	"NEMOCON",
		 	"NILO",
		 	"NIMAIMA",
		 	"NOCAIMA",
		 	"VENECIA",
		 	"PACHO",
		 	"PAIME",
		 	"PANDI",
		 	"PARATEBUENO",
		 	"PASCA",
		 	"PUERTO SALGAR",
		 	"PULI",
		 	"QUEBRADA NEGRA",
		 	"QUETAME",
		 	"QUIPILE",
		 	"APULO",
		 	"RICAURTE",
		 	"SAN ANTONIO DEL TEQUENDAMA",
		 	"SAN BERNARDO",
		 	"SAN CAYETANO",
		 	"SAN FRANCISCO",
		 	"SAN JUAN DE RIO SECO",
		 	"SASAIMA",
		 	"SESQUILE",
		 	"SIBATE",
		 	"SILVANIA",
		 	"SIMIJACA",
		 	"SOACHA",
		 	"SOPO",
		 	"SUBACHOQUE",
		 	"SUESCA",
		 	"SUPATA",
		 	"SUSA",
		 	"SUTATAUSA",
		 	"TABIO",
		 	"TAUSA",
		 	"TENA",
		 	"TENJO",
		 	"TIBACUY",
		 	"TIBIRITA",
		 	"TOCAIMA",
		 	"TOCANCIPA",
		 	"TOPAIPI",
		 	"UBALA",
		 	"UBAQUE",
		 	"UBATE",
		 	"UNE",
		 	"UTICA",
		 	"USME",
		 	"VERGARA",
		 	"VIANI",
		 	"VILLAGOMEZ",
		 	"VILLAPINZON",
		 	"VILLETA",
		 	"VIOTA",
		 	"YACOPI",
		 	"ZIPACON",
		 	"ZIPAQUIRA",
		 ],
		 "DISTRITO CAPITAL" => [
		 	"BOGOTA DISTRITO CAPITAL",
		 ],
		 "GUAINIA" => [
		 	"PUERTO INIRIDA",
		 	"BARRANCO MINAS",
		 	"MAPIRIPANA",
		 	"SAN FELIPE",
		 	"PUERTO COLOMBIA",
		 	"LA GUADALUPE",
		 	"CACAHUAL",
		 	"PANA PANA",
		 	"MORICHAL",
		 ],
		 "GUAVIARE" => [
		 	"SAN JOSE DEL GUAVIARE",
		 	"CALAMAR",
		 	"EL RETORNO",
		 	"MIRAFLORES",
		 ],
		 "HUILA" => [
		 	"NEIVA",
		 	"ACEVEDO",
		 	"AGRADO",
		 	"AIPE",
		 	"ALGECIRAS",
		 	"ALTAMIRA",
		 	"BARAYA",
		 	"CAMPOALEGRE",
		 	"COLOMBIA",
		 	"ELIAS",
		 	"GARZON",
		 	"GIGANTE",
		 	"GUADALUPE",
		 	"HOBO",
		 	"IQUIRA",
		 	"ISNOS",
		 	"LA ARGENTINA",
		 	"LA PLATA",
		 	"NATAGA",
		 	"OPORAPA",
		 	"PAICOL",
		 	"PALERMO",
		 	"PALESTINA",
		 	"EL PITAL",
		 	"PITALITO",
		 	"RIVERA",
		 	"SALADOBLANCO",
		 	"SAN AGUSTIN",
		 	"SANTA MARIA",
		 	"SUAZA",
		 	"TARQUI",
		 	"TESALIA (CARNICERIAS)",
		 	"TELLO",
		 	"TERUEL",
		 	"TIMANA",
		 	"VILLAVIEJA",
		 	"YAGUARA",
		 ],
		 "LA GUAJIRA" => [
		 	"RIOHACHA",
		 	"ALBANIA",
		 	"BARRANCAS",
		 	"DIBULLA",
		 	"DISTRACCION",
		 	"EL MOLINO",
		 	"FONSECA",
		 	"HATO NUEVO",
		 	"JAGUA DEL PILAR",
		 	"MAICAO",
		 	"MANAURE",
		 	"SAN JUAN DEL CESAR",
		 	"URIBIA",
		 	"URUMITA",
		 	"VILLA NUEVA",
		 ],
		 "MAGDALENA" => [
		 	"SANTA MARTA",
		 	"ALGARROBO",
		 	"ARACATACA",
		 	"ARIGUANI (EL DIFICIL)",
		 	"CERRO DE SAN ANTONIO",
		 	"CHIVOLO",
		 	"CIENAGA",
		 	"CONCORDIA",
		 	"EL BANCO",
		 	"EL PIÑON",
		 	"EL RETEN",
		 	"FUNDACION",
		 	"GUAMAL",
		 	"NUEVA GRANADA",
		 	"PEDRAZA",
		 	"PIJIÑO DEL CARMEN",
		 	"PIVIJAY",
		 	"PLATO",
		 	"PUEBLO VIEJO",
		 	"REMOLINO",
		 	"SABANAS DE SAN ANGEL",
		 	"SALAMINA",
		 	"SAN SEBASTIAN DE BUENAVISTA",
		 	"SAN ZENON",
		 	"SANTA ANA",
		 	"SANTA BARBARA DE PINTO",
		 	"SITIONUEVO",
		 	"TENERIFE",
		 	"ZAPAYAN",
		 	"ZONA BANANERA",
		 ],
		 "META" => [
		 	"VILLAVICENCIO",
		 	"ACACIAS",
		 	"BARRANCA DE UPIA",
		 	"CABUYARO",
		 	"CASTILLA LA NUEVA",
		 	"CUBARRAL",
		 	"CUMARAL",
		 	"EL CALVARIO",
		 	"EL CASTILLO",
		 	"EL DORADO",
		 	"FUENTE DE ORO",
		 	"GRANADA",
		 	"GUAMAL",
		 	"MAPIRIPAN",
		 	"MESETAS",
		 	"LA MACARENA",
		 	"LA URIBE",
		 	"LEJANIAS",
		 	"PUERTO CONCORDIA",
		 	"PUERTO GAITAN",
		 	"PUERTO LOPEZ",
		 	"PUERTO LLERAS",
		 	"PUERTO RICO",
		 	"RESTREPO",
		 	"SAN CARLOS DE GUAROA",
		 	"SAN JUAN DE ARAMA",
		 	"SAN JUANITO",
		 	"SAN MARTIN",
		 	"VISTA HERMOSA",
		 ],
		 "NARIÑO" => [
		 	"PASTO",
		 	"ALBAN - SAN JOSE",
		 	"ALDANA",
		 	"ANCUYA",
		 	"ARBOLEDA",
		 	"BARBACOAS",
		 	"BELEN",
		 	"BUESACO",
		 	"COLON (GENOVA)",
		 	"CONSACA",
		 	"CONTADERO",
		 	"CORDOBA",
		 	"CUASPUD (CARLOS)",
		 	"CUMBAL",
		 	"CUMBITARA",
		 	"CHACHAGÜI",
		 	"EL CHARCO",
		 	"EL PEÑOL",
		 	"EL ROSARIO",
		 	"EL TABLON DE GOMEZ",
		 	"EL TAMBO",
		 	"FUNES",
		 	"GUACHUCAL",
		 	"GUAITARILLA",
		 	"GUALMATAN",
		 	"ILES",
		 	"IMUES",
		 	"IPIALES",
		 	"LA CRUZ",
		 	"LA FLORIDA",
		 	"LA LLANADA",
		 	"LA TOLA",
		 	"LA UNION",
		 	"LEIVA",
		 	"LINARES",
		 	"LOS ANDES - SOTOMAYOR",
		 	"MAGÜI PAYAN",
		 	"MALLAMA - PIEDRANCHA",
		 	"MOSQUERA",
		 	"NARIÑO",
		 	"OLAYA HERRERA",
		 	"OSPINA",
		 	"FRANCISCO PIZARRO",
		 	"POLICARPA",
		 	"POTOSI",
		 	"PROVIDENCIA",
		 	"PUERRES",
		 	"PUPIALES",
		 	"RICAURTE",
		 	"ROBERTO PAYAN",
		 	"SAMANIEGO",
		 	"SANDONA",
		 	"SAN BERNARDO",
		 	"SAN LORENZO",
		 	"SAN PABLO",
		 	"SAN PEDRO DE CARTAGO",
		 	"SANTA BARBARA",
		 	"SANTACRUZ GUACHAVEZ",
		 	"SAPUYES",
		 	"TAMINANGO",
		 	"TANGUA",
		 	"TUMACO",
		 	"TUQUERRES",
		 	"YACUANQUER",
		 ],
		 "NORTE DE SANTANDER" => [
		 	"CUCUTA",
		 	"ABREGO",
		 	"ARBOLEDAS",
		 	"BOCHALEMA",
		 	"BUCARASICA",
		 	"CACOTA",
		 	"CACHIRA",
		 	"CHINACOTA",
		 	"CHITAGA",
		 	"CONVENCION",
		 	"CUCUTILLA",
		 	"DURANIA",
		 	"EL CARMEN",
		 	"EL TARRA",
		 	"EL ZULIA",
		 	"GRAMALOTE",
		 	"HACARI",
		 	"HERRAN",
		 	"LA BATECA",
		 	"LA ESPERANZA",
		 	"LA PLAYA",
		 	"LOS PATIOS",
		 	"LOURDES",
		 	"MUTISCUA",
		 	"OCAÑA",
		 	"PAMPLONA",
		 	"PAMPLONITA",
		 	"PUERTO SANTANDER",
		 	"RAGONVALIA",
		 	"SALAZAR",
		 	"SAN CALIXTO",
		 	"SAN CAYETANO",
		 	"SANTIAGO",
		 	"SARDINATA",
		 	"SILOS",
		 	"TEORAMA",
		 	"TIBU",
		 	"TOLEDO",
		 	"VILLA CARO",
		 	"VILLA ROSARIO",
		 ],


		 "PUTUMAYO" => [
			"COLÓN",
			"MOCOA",
			"ORITO",
			"PUERTO ASIS",
			"PUERTO CAICEDO",
			"PUERTO GÚZMAN",
			"PUERTO LEGUIZAMO",
			"SAN FRANCISCO",
			"SAN MIGUEL",
			"SANTIAGO",
			"SIBUNDOY",
			"VALLE DELGUAMUEZ",
			"VILLAGARZÓN",
		],
		 "QUINDIO" => [
		 	"ARMENIA",
		 	"BUENAVISTA",
		 	"CALARCA",
		 	"CIRCASIA",
		 	"BARCELONA",
		 	"CORDOBA",
		 	"FILANDIA",
		 	"GENOVA",
		 	"LA TEBAIDA",
		 	"MONTENEGRO",
		 	"PIJAO",
		 	"QUIMBAYA",
		 	"SALENTO",
		 ],

		 "RISARALDA" => [
		 	"CALDAS",
		 	"PEREIRA",
		 	"APIA",
		 	"BALBOA",
		 	"BELEN DE UMBRIA",
		 	"DOSQUEBRADAS",
		 	"GUATICA",
		 	"LA CELIA",
		 	"LA VIRGINIA",
		 	"MARSELLA",
		 	"MISTRATO",
		 	"PUEBLO RICO",
		 	"QUINCHIA",
		 	"SANTA ROSA DE CABAL",
		 	"SANTUARIO",
		 ],
		 "SANTANDER" => [
		 	"BUCARAMANGA",
		 	"AGUADA",
		 	"ALBANIA",
		 	"ARATOCA",
		 	"BARBOSA",
		 	"BARICHARA",
		 	"BARRANCABERMEJA",
		 	"BETUNIA",
		 	"BOLIVAR",
		 	"CABRERA",
		 	"CALIFORNIA",
		 	"CAPITANEJO",
		 	"CARCASI",
		 	"CEPITA",
		 	"CERRITO",
		 	"CHARALA",
		 	"CHARTA",
		 	"CHIMA",
		 	"CHIPATA",
		 	"CIMITARRA",
		 	"CONCEPCION",
		 	"CONFINES",
		 	"CONTRATACION",
		 	"COROMORO",
		 	"CURITI",
		 	"EL CARMEN DE CHUCURI",
		 	"EL GUACAMAYO",
		 	"EL PEÑON",
		 	"EL PLAYON",
		 	"ENCINO",
		 	"ENCISO",
		 	"FLORIAN",
		 	"FLORIDABLANCA",
		 	"GALAN",
		 	"GAMBITA",
		 	"GIRON",
		 	"GUACA",
		 	"GUADALUPE",
		 	"GUAPOTA",
		 	"GUAVATA",
		 	"GÜEPSA",
		 	"HATO",
		 	"JESUS MARIA",
		 	"JORDAN",
		 	"LA BELLEZA",
		 	"LANDAZURI",
		 	"LA PAZ",
		 	"LEBRIJA",
		 	"LOS SANTOS",
		 	"MACARAVITA",
		 	"MALAGA",
		 	"MATANZA",
		 	"MOGOTES",
		 	"MOLAGAVITA",
		 	"OCAMONTE",
		 	"OIBA",
		 	"ONZAGA",
		 	"PALMAR",
		 	"PALMAS DEL SOCORRO",
		 	"PARAMO",
		 	"PIEDECUESTA",
		 	"PINCHOTE",
		 	"PUENTE NACIONAL",
		 	"PUERTO PARRA",
		 	"PUERTO WILCHES",
		 	"RIONEGRO",
		 	"SABANA DE TORRES",
		 	"SAN ANDRES",
		 	"SAN BENITO",
		 	"SAN GIL",
		 	"SAN JOAQUIN",
		 	"SAN JOSE DE MIRANDA",
		 	"SAN MIGUEL",
		 	"SAN VICENTE DE CHUCURI",
		 	"SANTA BARBARA",
		 	"SANTA HELENA DEL OPON",
		 	"SIMACOTA",
		 	"SOCORRO",
		 	"SUAITA",
		 	"SUCRE",
		 	"SURATA",
		 	"TONA",
		 	"VALLE DE SAN JOSE",
		 	"VELEZ",
		 	"VETAS",
		 	"VILLANUEVA",
		 	"ZAPATOCA",
		 ],
		 "SUCRE" => [
		 	"SINCELEJO",
		 	"BUENAVISTA",
		 	"CAIMITO",
		 	"COLOSO (RICAURTE)",
		 	"COROZAL",
		 	"CHALAN",
		 	"EL ROBLE",
		 	"GALERAS",
		 	"GUARANDA",
		 	"LA UNION",
		 	"LOS PALMITOS",
		 	"MAJAGUAL",
		 	"MORROA",
		 	"OVEJAS",
		 	"PALMITO",
		 	"SAMPUES",
		 	"SAN BENITO ABAD",
		 	"SAN JUAN DE BETULIA",
		 	"SAN MARCOS",
		 	"SAN ONOFRE",
		 	"SAN PEDRO",
		 	"SINCE",
		 	"SUCRE",
		 	"TOLU",
		 	"COVEÑAS",
		 	"TOLUVIEJO",
		 ],
		 "TOLIMA" => [
		 	"IBAGUE",
		 	"ALPUJARRA",
		 	"ALVARADO",
		 	"AMBALEMA",
		 	"ANZOATEGUI",
		 	"ARMERO",
		 	"ATACO",
		 	"CAJAMARCA",
		 	"CARMEN DE APICALA",
		 	"CASABIANCA",
		 	"CHAPARRAL",
		 	"BUENOS AIRES",
		 	"COELLO",
		 	"COYAIMA",
		 	"CUNDAY",
		 	"DOLORES",
		 	"ESPINAL",
		 	"FALAN",
		 	"FLANDES",
		 	"FRESNO",
		 	"GUAMO",
		 	"LA SIERRA",
		 	"HERVEO",
		 	"HONDA",
		 	"ICONONZO",
		 	"LERIDA",
		 	"LIBANO",
		 	"MARIQUITA",
		 	"MELGAR",
		 	"MURILLO",
		 	"NATAGAIMA",
		 	"ORTEGA",
		 	"PALO CABILDO",
		 	"PIEDRAS",
		 	"PLANADAS",
		 	"PRADO",
		 	"PURIFICACION",
		 	"RIOBLANCO",
		 	"RONCESVALLES",
		 	"ROVIRA",
		 	"SALDAÑA",
		 	"SAN ANTONIO",
		 	"SAN LUIS",
		 	"SANTA ISABEL",
		 	"SUAREZ",
		 	"VALLE DE SAN JUAN",
		 	"VENADILLO",
		 	"VILLAHERMOSA",
		 	"VILLARRICA",
		 ],
		 "VALLE DEL CAUCA" => [
		 	"CALI",
		 	"ALCALA",
		 	"ANDALUCIA",
		 	"ANSERMANUEVO",
		 	"ARGELIA",
		 	"BOLIVAR",
		 	"BUENAVENTURA",
		 	"BUGA",
		 	"BUGALAGRANDE",
		 	"CAICEDONIA",
		 	"CALIMA",
		 	"CANDELARIA",
		 	"CARTAGO",
		 	"DAGUA",
		 	"EL AGUILA",
		 	"EL CAIRO",
		 	"EL CERRITO",
		 	"EL DOVIO",
		 	"FLORIDA",
		 	"GINEBRA",
		 	"GUACARI",
		 	"JAMUNDI",
		 	"LA CUMBRE",
		 	"LA UNION",
		 	"LA VICTORIA",
		 	"OBANDO",
		 	"PALMIRA",
		 	"PRADERA",
		 	"RESTREPO",
		 	"RIOFRIO",
		 	"ROLDANILLO",
		 	"SAN PEDRO",
		 	"SEVILLA",
		 	"TORO",
		 	"TRUJILLO",
		 	"TULUA",
		 	"ULLOA",
		 	"VERSALLES",
		 	"VIJES",
		 	"YOTOCO",
		 	"YUMBO",
		 	"ZARZAL",
		 ],
		 "VAUPES" => [
		 	"MITU",
		 	"CARURU",
		 	"PACOA",
		 	"TARAIRA",
		 	"PAPUNAUA",
		 	"YAVARATE",
		 ],
		 "VICHADA" => [
		 	"PUERTO CARREÑO",
		 	"LA PRIMAVERA",
		 	"SANTA ROSALIA",
		 	"CUMARIBO",
		 ]
	]
);

$ciudades2 = [];

foreach ($config["DEPARTAMENTOS"] as $key => $value) {
	foreach ($config["CIUDADES"][$value] as $keyC => $valueC) {
		$ciudades2[$value][$valueC] = $valueC;
	}
}

$config["CIUDADES"] = $ciudades2;

?>

